language: objective-c
cache:
  - cocoapods
notifications:
  email:
    - travis%0045ci%0045mobile%0045ios+b4e6d7755fa5e685126a5015e80e37f3@streams.zulip.com
before_install:
  - sudo systemsetup -gettimezone
  - sudo systemsetup -settimezone America/New_York
  - rm -rf ~/Library/Developer/Xcode/DerivedData/*
script: bundle exec ruby travis.rb
